modLoader="javafml"
loaderVersion="[30,)"
[[mods]]
    modId="tramplestopper"
    version="${file.jarVersion}"
    displayName="Trample Stopper"
    description="Stops crop trampling"
    license="ARR"